// File generated from our OpenAPI spec by Stainless.

package com.clearstreet.api.models.v1.screener

import com.clearstreet.api.core.JsonValue
import com.clearstreet.api.core.jsonMapper
import com.clearstreet.api.models.ApiError
import com.clearstreet.api.models.ResponseMetadata
import com.clearstreet.api.models.v1.SortDirection
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ScreenerReplaceScreenerResponseTest {

    @Test
    fun create() {
        val screenerReplaceScreenerResponse =
            ScreenerReplaceScreenerResponse.builder()
                .metadata(
                    ResponseMetadata.builder()
                        .requestId("request_id")
                        .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .pageNumber(0)
                        .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .totalItems(0L)
                        .totalPages(0)
                        .build()
                )
                .error(
                    ApiError.builder()
                        .code(400)
                        .message("Order quantity must be greater than zero")
                        .addDetail(
                            ApiError.Detail.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .data(
                    ScreenerEntry.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addFilter(
                            SearchFilter.builder()
                                .left(
                                    FieldRef.builder()
                                        .name("market_cap")
                                        .lookback(FieldLookback.ONE_DAY)
                                        .period(FieldPeriod.QUARTER)
                                        .valueType(FieldType.DECIMAL)
                                        .build()
                                )
                                .op(
                                    FilterOpSpec.builder()
                                        .name(FilterOperator.LESS_THAN)
                                        .addArg(OperatorArg.LEFT_INCLUSIVE)
                                        .build()
                                )
                                .addRight(
                                    FilterValue.builder()
                                        .value(1000000000.0)
                                        .variable(
                                            Variable.builder()
                                                .name("today")
                                                .lookback(FieldLookback.ONE_DAY)
                                                .modifier(
                                                    Modifier.builder()
                                                        .addArg(30.0)
                                                        .addArg("DAY")
                                                        .name(ModifierOp.SUBTRACT)
                                                        .build()
                                                )
                                                .period(FieldPeriod.QUARTER)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .name("name")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addColumn(
                            FieldRef.builder()
                                .name("market_cap")
                                .lookback(FieldLookback.ONE_DAY)
                                .period(FieldPeriod.QUARTER)
                                .valueType(FieldType.DECIMAL)
                                .build()
                        )
                        .addFieldFilter(
                            FieldRef.builder()
                                .name("market_cap")
                                .lookback(FieldLookback.ONE_DAY)
                                .period(FieldPeriod.QUARTER)
                                .valueType(FieldType.DECIMAL)
                                .build()
                        )
                        .addSort(
                            SortSpec.builder()
                                .field(
                                    FieldRef.builder()
                                        .name("market_cap")
                                        .lookback(FieldLookback.ONE_DAY)
                                        .period(FieldPeriod.QUARTER)
                                        .valueType(FieldType.DECIMAL)
                                        .build()
                                )
                                .direction(SortDirection.DESC)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(screenerReplaceScreenerResponse.metadata())
            .isEqualTo(
                ResponseMetadata.builder()
                    .requestId("request_id")
                    .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                    .pageNumber(0)
                    .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                    .totalItems(0L)
                    .totalPages(0)
                    .build()
            )
        assertThat(screenerReplaceScreenerResponse.error())
            .contains(
                ApiError.builder()
                    .code(400)
                    .message("Order quantity must be greater than zero")
                    .addDetail(
                        ApiError.Detail.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(screenerReplaceScreenerResponse.data())
            .isEqualTo(
                ScreenerEntry.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addFilter(
                        SearchFilter.builder()
                            .left(
                                FieldRef.builder()
                                    .name("market_cap")
                                    .lookback(FieldLookback.ONE_DAY)
                                    .period(FieldPeriod.QUARTER)
                                    .valueType(FieldType.DECIMAL)
                                    .build()
                            )
                            .op(
                                FilterOpSpec.builder()
                                    .name(FilterOperator.LESS_THAN)
                                    .addArg(OperatorArg.LEFT_INCLUSIVE)
                                    .build()
                            )
                            .addRight(
                                FilterValue.builder()
                                    .value(1000000000.0)
                                    .variable(
                                        Variable.builder()
                                            .name("today")
                                            .lookback(FieldLookback.ONE_DAY)
                                            .modifier(
                                                Modifier.builder()
                                                    .addArg(30.0)
                                                    .addArg("DAY")
                                                    .name(ModifierOp.SUBTRACT)
                                                    .build()
                                            )
                                            .period(FieldPeriod.QUARTER)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .name("name")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addColumn(
                        FieldRef.builder()
                            .name("market_cap")
                            .lookback(FieldLookback.ONE_DAY)
                            .period(FieldPeriod.QUARTER)
                            .valueType(FieldType.DECIMAL)
                            .build()
                    )
                    .addFieldFilter(
                        FieldRef.builder()
                            .name("market_cap")
                            .lookback(FieldLookback.ONE_DAY)
                            .period(FieldPeriod.QUARTER)
                            .valueType(FieldType.DECIMAL)
                            .build()
                    )
                    .addSort(
                        SortSpec.builder()
                            .field(
                                FieldRef.builder()
                                    .name("market_cap")
                                    .lookback(FieldLookback.ONE_DAY)
                                    .period(FieldPeriod.QUARTER)
                                    .valueType(FieldType.DECIMAL)
                                    .build()
                            )
                            .direction(SortDirection.DESC)
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val screenerReplaceScreenerResponse =
            ScreenerReplaceScreenerResponse.builder()
                .metadata(
                    ResponseMetadata.builder()
                        .requestId("request_id")
                        .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .pageNumber(0)
                        .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .totalItems(0L)
                        .totalPages(0)
                        .build()
                )
                .error(
                    ApiError.builder()
                        .code(400)
                        .message("Order quantity must be greater than zero")
                        .addDetail(
                            ApiError.Detail.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .data(
                    ScreenerEntry.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addFilter(
                            SearchFilter.builder()
                                .left(
                                    FieldRef.builder()
                                        .name("market_cap")
                                        .lookback(FieldLookback.ONE_DAY)
                                        .period(FieldPeriod.QUARTER)
                                        .valueType(FieldType.DECIMAL)
                                        .build()
                                )
                                .op(
                                    FilterOpSpec.builder()
                                        .name(FilterOperator.LESS_THAN)
                                        .addArg(OperatorArg.LEFT_INCLUSIVE)
                                        .build()
                                )
                                .addRight(
                                    FilterValue.builder()
                                        .value(1000000000.0)
                                        .variable(
                                            Variable.builder()
                                                .name("today")
                                                .lookback(FieldLookback.ONE_DAY)
                                                .modifier(
                                                    Modifier.builder()
                                                        .addArg(30.0)
                                                        .addArg("DAY")
                                                        .name(ModifierOp.SUBTRACT)
                                                        .build()
                                                )
                                                .period(FieldPeriod.QUARTER)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .name("name")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addColumn(
                            FieldRef.builder()
                                .name("market_cap")
                                .lookback(FieldLookback.ONE_DAY)
                                .period(FieldPeriod.QUARTER)
                                .valueType(FieldType.DECIMAL)
                                .build()
                        )
                        .addFieldFilter(
                            FieldRef.builder()
                                .name("market_cap")
                                .lookback(FieldLookback.ONE_DAY)
                                .period(FieldPeriod.QUARTER)
                                .valueType(FieldType.DECIMAL)
                                .build()
                        )
                        .addSort(
                            SortSpec.builder()
                                .field(
                                    FieldRef.builder()
                                        .name("market_cap")
                                        .lookback(FieldLookback.ONE_DAY)
                                        .period(FieldPeriod.QUARTER)
                                        .valueType(FieldType.DECIMAL)
                                        .build()
                                )
                                .direction(SortDirection.DESC)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedScreenerReplaceScreenerResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(screenerReplaceScreenerResponse),
                jacksonTypeRef<ScreenerReplaceScreenerResponse>(),
            )

        assertThat(roundtrippedScreenerReplaceScreenerResponse)
            .isEqualTo(screenerReplaceScreenerResponse)
    }
}
