// File generated from our OpenAPI spec by Stainless.

package com.clear_street.api.models.active.v1.screener

import com.clear_street.api.core.JsonValue
import com.clear_street.api.core.jsonMapper
import com.clear_street.api.models.ApiError
import com.clear_street.api.models.ResponseMetadata
import com.clear_street.api.models.active.v1.SecurityIdSource
import com.clear_street.api.models.active.v1.instruments.AnalystRating
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.LocalDate
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ScreenerGetScreenerResponseTest {

    @Test
    fun create() {
        val screenerGetScreenerResponse =
            ScreenerGetScreenerResponse.builder()
                .metadata(
                    ResponseMetadata.builder()
                        .requestId("request_id")
                        .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .pageNumber(0)
                        .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .totalItems(0L)
                        .totalPages(0)
                        .build()
                )
                .error(
                    ApiError.builder()
                        .code(400)
                        .message("Order quantity must be greater than zero")
                        .addDetail(
                            ApiError.Detail.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .addData(
                    ScreenerItem.builder()
                        .buyRatings(15)
                        .holdRatings(5)
                        .price("175.05")
                        .securityId("AAPL")
                        .securityIdSource(SecurityIdSource.CMS)
                        .sellRatings(2)
                        .strongBuyRatings(10)
                        .strongSellRatings(1)
                        .symbol("AAPL")
                        .totalRatings(33)
                        .consensusPriceTarget("200.00")
                        .consensusPriceTargetHigh("250.00")
                        .consensusPriceTargetLow("150.00")
                        .consensusRating(AnalystRating.STRONG_BUY)
                        .countryOfIssue("US")
                        .description("Apple Inc. designs, manufactures, and markets smartphones...")
                        .fiftyTwoWeekHigh("230.00")
                        .fiftyTwoWeekLow("165.00")
                        .gapFrom52wHighPct("-8.50")
                        .gapFrom52wLowPct("42.30")
                        .industry("Consumer Electronics")
                        .listDate(LocalDate.parse("1980-12-12"))
                        .marketCap("2800000000000")
                        .monthAvgVolume("23000000")
                        .name("Apple Inc.")
                        .oneMonthAgoClose("one_month_ago_close")
                        .oneMonthAgoOpen("one_month_ago_open")
                        .oneMonthChangePct("5.12")
                        .oneWeekAgoClose("one_week_ago_close")
                        .oneWeekAgoOpen("one_week_ago_open")
                        .oneWeekChangePct("2.35")
                        .oneYearAgoClose("one_year_ago_close")
                        .oneYearAgoOpen("one_year_ago_open")
                        .oneYearChangePct("one_year_change_pct")
                        .percentChange("2.5")
                        .prevDayClose("171.00")
                        .sector("Technology")
                        .securityType("COMMON_STOCK")
                        .sixMonthChangePct("six_month_change_pct")
                        .sixMonthsAgoClose("six_months_ago_close")
                        .sixMonthsAgoOpen("six_months_ago_open")
                        .threeMonthChangePct("three_month_change_pct")
                        .threeMonthsAgoClose("three_months_ago_close")
                        .threeMonthsAgoOpen("three_months_ago_open")
                        .ttmDebtToEquity("1.5")
                        .ttmDividendYield("6.5")
                        .ttmEarningsPerShare("5.61")
                        .ttmPriceToEarnings("30.5")
                        .venue("XNMS")
                        .volume("25000000")
                        .weekAvgVolume("22000000")
                        .yearToDateOpen("year_to_date_open")
                        .ytdChangePct("12.50")
                        .build()
                )
                .build()

        assertThat(screenerGetScreenerResponse.metadata())
            .isEqualTo(
                ResponseMetadata.builder()
                    .requestId("request_id")
                    .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                    .pageNumber(0)
                    .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                    .totalItems(0L)
                    .totalPages(0)
                    .build()
            )
        assertThat(screenerGetScreenerResponse.error())
            .contains(
                ApiError.builder()
                    .code(400)
                    .message("Order quantity must be greater than zero")
                    .addDetail(
                        ApiError.Detail.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(screenerGetScreenerResponse.data())
            .containsExactly(
                ScreenerItem.builder()
                    .buyRatings(15)
                    .holdRatings(5)
                    .price("175.05")
                    .securityId("AAPL")
                    .securityIdSource(SecurityIdSource.CMS)
                    .sellRatings(2)
                    .strongBuyRatings(10)
                    .strongSellRatings(1)
                    .symbol("AAPL")
                    .totalRatings(33)
                    .consensusPriceTarget("200.00")
                    .consensusPriceTargetHigh("250.00")
                    .consensusPriceTargetLow("150.00")
                    .consensusRating(AnalystRating.STRONG_BUY)
                    .countryOfIssue("US")
                    .description("Apple Inc. designs, manufactures, and markets smartphones...")
                    .fiftyTwoWeekHigh("230.00")
                    .fiftyTwoWeekLow("165.00")
                    .gapFrom52wHighPct("-8.50")
                    .gapFrom52wLowPct("42.30")
                    .industry("Consumer Electronics")
                    .listDate(LocalDate.parse("1980-12-12"))
                    .marketCap("2800000000000")
                    .monthAvgVolume("23000000")
                    .name("Apple Inc.")
                    .oneMonthAgoClose("one_month_ago_close")
                    .oneMonthAgoOpen("one_month_ago_open")
                    .oneMonthChangePct("5.12")
                    .oneWeekAgoClose("one_week_ago_close")
                    .oneWeekAgoOpen("one_week_ago_open")
                    .oneWeekChangePct("2.35")
                    .oneYearAgoClose("one_year_ago_close")
                    .oneYearAgoOpen("one_year_ago_open")
                    .oneYearChangePct("one_year_change_pct")
                    .percentChange("2.5")
                    .prevDayClose("171.00")
                    .sector("Technology")
                    .securityType("COMMON_STOCK")
                    .sixMonthChangePct("six_month_change_pct")
                    .sixMonthsAgoClose("six_months_ago_close")
                    .sixMonthsAgoOpen("six_months_ago_open")
                    .threeMonthChangePct("three_month_change_pct")
                    .threeMonthsAgoClose("three_months_ago_close")
                    .threeMonthsAgoOpen("three_months_ago_open")
                    .ttmDebtToEquity("1.5")
                    .ttmDividendYield("6.5")
                    .ttmEarningsPerShare("5.61")
                    .ttmPriceToEarnings("30.5")
                    .venue("XNMS")
                    .volume("25000000")
                    .weekAvgVolume("22000000")
                    .yearToDateOpen("year_to_date_open")
                    .ytdChangePct("12.50")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val screenerGetScreenerResponse =
            ScreenerGetScreenerResponse.builder()
                .metadata(
                    ResponseMetadata.builder()
                        .requestId("request_id")
                        .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .pageNumber(0)
                        .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .totalItems(0L)
                        .totalPages(0)
                        .build()
                )
                .error(
                    ApiError.builder()
                        .code(400)
                        .message("Order quantity must be greater than zero")
                        .addDetail(
                            ApiError.Detail.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .addData(
                    ScreenerItem.builder()
                        .buyRatings(15)
                        .holdRatings(5)
                        .price("175.05")
                        .securityId("AAPL")
                        .securityIdSource(SecurityIdSource.CMS)
                        .sellRatings(2)
                        .strongBuyRatings(10)
                        .strongSellRatings(1)
                        .symbol("AAPL")
                        .totalRatings(33)
                        .consensusPriceTarget("200.00")
                        .consensusPriceTargetHigh("250.00")
                        .consensusPriceTargetLow("150.00")
                        .consensusRating(AnalystRating.STRONG_BUY)
                        .countryOfIssue("US")
                        .description("Apple Inc. designs, manufactures, and markets smartphones...")
                        .fiftyTwoWeekHigh("230.00")
                        .fiftyTwoWeekLow("165.00")
                        .gapFrom52wHighPct("-8.50")
                        .gapFrom52wLowPct("42.30")
                        .industry("Consumer Electronics")
                        .listDate(LocalDate.parse("1980-12-12"))
                        .marketCap("2800000000000")
                        .monthAvgVolume("23000000")
                        .name("Apple Inc.")
                        .oneMonthAgoClose("one_month_ago_close")
                        .oneMonthAgoOpen("one_month_ago_open")
                        .oneMonthChangePct("5.12")
                        .oneWeekAgoClose("one_week_ago_close")
                        .oneWeekAgoOpen("one_week_ago_open")
                        .oneWeekChangePct("2.35")
                        .oneYearAgoClose("one_year_ago_close")
                        .oneYearAgoOpen("one_year_ago_open")
                        .oneYearChangePct("one_year_change_pct")
                        .percentChange("2.5")
                        .prevDayClose("171.00")
                        .sector("Technology")
                        .securityType("COMMON_STOCK")
                        .sixMonthChangePct("six_month_change_pct")
                        .sixMonthsAgoClose("six_months_ago_close")
                        .sixMonthsAgoOpen("six_months_ago_open")
                        .threeMonthChangePct("three_month_change_pct")
                        .threeMonthsAgoClose("three_months_ago_close")
                        .threeMonthsAgoOpen("three_months_ago_open")
                        .ttmDebtToEquity("1.5")
                        .ttmDividendYield("6.5")
                        .ttmEarningsPerShare("5.61")
                        .ttmPriceToEarnings("30.5")
                        .venue("XNMS")
                        .volume("25000000")
                        .weekAvgVolume("22000000")
                        .yearToDateOpen("year_to_date_open")
                        .ytdChangePct("12.50")
                        .build()
                )
                .build()

        val roundtrippedScreenerGetScreenerResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(screenerGetScreenerResponse),
                jacksonTypeRef<ScreenerGetScreenerResponse>(),
            )

        assertThat(roundtrippedScreenerGetScreenerResponse).isEqualTo(screenerGetScreenerResponse)
    }
}
