// File generated from our OpenAPI spec by Stainless.

package com.clear_street.api.models.active.v1.screener

import com.clear_street.api.core.jsonMapper
import com.clear_street.api.models.active.v1.SecurityIdSource
import com.clear_street.api.models.active.v1.instruments.AnalystRating
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.LocalDate
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ScreenerItemTest {

    @Test
    fun create() {
        val screenerItem =
            ScreenerItem.builder()
                .price("175.05")
                .securityId("AAPL")
                .securityIdSource(SecurityIdSource.CMS)
                .symbol("AAPL")
                .totalRatings(33)
                .consensusPriceTarget("200.00")
                .consensusRating(AnalystRating.STRONG_BUY)
                .countryOfIssue("US")
                .debtToEquityTtm("1.5")
                .description("Apple Inc. designs, manufactures, and markets smartphones...")
                .dividendYieldTtm("6.5")
                .earningsPerShareTtm("5.61")
                .exchange("XNMS")
                .fiftyTwoWeekHigh("230.00")
                .fiftyTwoWeekLow("165.00")
                .gapFrom52wHighPct("-8.50")
                .gapFrom52wLowPct("42.30")
                .industry("Consumer Electronics")
                .listDate(LocalDate.parse("1980-12-12"))
                .marketCap("2800000000000")
                .monthAvgVolume("23000000")
                .name("Apple Inc.")
                .oneMonthAgoClose("one_month_ago_close")
                .oneMonthAgoOpen("one_month_ago_open")
                .oneMonthChangePct("5.12")
                .oneWeekAgoClose("one_week_ago_close")
                .oneWeekAgoOpen("one_week_ago_open")
                .oneWeekChangePct("2.35")
                .oneYearAgoClose("one_year_ago_close")
                .oneYearAgoOpen("one_year_ago_open")
                .oneYearChangePct("one_year_change_pct")
                .percentChange("2.5")
                .prevDayClose("171.00")
                .priceToEarningsTtm("30.5")
                .sector("Technology")
                .securityType("COMMON_STOCK")
                .sixMonthChangePct("six_month_change_pct")
                .sixMonthsAgoClose("six_months_ago_close")
                .sixMonthsAgoOpen("six_months_ago_open")
                .threeMonthChangePct("three_month_change_pct")
                .threeMonthsAgoClose("three_months_ago_close")
                .threeMonthsAgoOpen("three_months_ago_open")
                .volume("25000000")
                .weekAvgVolume("22000000")
                .yearToDateOpen("year_to_date_open")
                .ytdChangePct("12.50")
                .build()

        assertThat(screenerItem.price()).isEqualTo("175.05")
        assertThat(screenerItem.securityId()).isEqualTo("AAPL")
        assertThat(screenerItem.securityIdSource()).isEqualTo(SecurityIdSource.CMS)
        assertThat(screenerItem.symbol()).isEqualTo("AAPL")
        assertThat(screenerItem.totalRatings()).isEqualTo(33)
        assertThat(screenerItem.consensusPriceTarget()).contains("200.00")
        assertThat(screenerItem.consensusRating()).contains(AnalystRating.STRONG_BUY)
        assertThat(screenerItem.countryOfIssue()).contains("US")
        assertThat(screenerItem.debtToEquityTtm()).contains("1.5")
        assertThat(screenerItem.description())
            .contains("Apple Inc. designs, manufactures, and markets smartphones...")
        assertThat(screenerItem.dividendYieldTtm()).contains("6.5")
        assertThat(screenerItem.earningsPerShareTtm()).contains("5.61")
        assertThat(screenerItem.exchange()).contains("XNMS")
        assertThat(screenerItem.fiftyTwoWeekHigh()).contains("230.00")
        assertThat(screenerItem.fiftyTwoWeekLow()).contains("165.00")
        assertThat(screenerItem.gapFrom52wHighPct()).contains("-8.50")
        assertThat(screenerItem.gapFrom52wLowPct()).contains("42.30")
        assertThat(screenerItem.industry()).contains("Consumer Electronics")
        assertThat(screenerItem.listDate()).contains(LocalDate.parse("1980-12-12"))
        assertThat(screenerItem.marketCap()).contains("2800000000000")
        assertThat(screenerItem.monthAvgVolume()).contains("23000000")
        assertThat(screenerItem.name()).contains("Apple Inc.")
        assertThat(screenerItem.oneMonthAgoClose()).contains("one_month_ago_close")
        assertThat(screenerItem.oneMonthAgoOpen()).contains("one_month_ago_open")
        assertThat(screenerItem.oneMonthChangePct()).contains("5.12")
        assertThat(screenerItem.oneWeekAgoClose()).contains("one_week_ago_close")
        assertThat(screenerItem.oneWeekAgoOpen()).contains("one_week_ago_open")
        assertThat(screenerItem.oneWeekChangePct()).contains("2.35")
        assertThat(screenerItem.oneYearAgoClose()).contains("one_year_ago_close")
        assertThat(screenerItem.oneYearAgoOpen()).contains("one_year_ago_open")
        assertThat(screenerItem.oneYearChangePct()).contains("one_year_change_pct")
        assertThat(screenerItem.percentChange()).contains("2.5")
        assertThat(screenerItem.prevDayClose()).contains("171.00")
        assertThat(screenerItem.priceToEarningsTtm()).contains("30.5")
        assertThat(screenerItem.sector()).contains("Technology")
        assertThat(screenerItem.securityType()).contains("COMMON_STOCK")
        assertThat(screenerItem.sixMonthChangePct()).contains("six_month_change_pct")
        assertThat(screenerItem.sixMonthsAgoClose()).contains("six_months_ago_close")
        assertThat(screenerItem.sixMonthsAgoOpen()).contains("six_months_ago_open")
        assertThat(screenerItem.threeMonthChangePct()).contains("three_month_change_pct")
        assertThat(screenerItem.threeMonthsAgoClose()).contains("three_months_ago_close")
        assertThat(screenerItem.threeMonthsAgoOpen()).contains("three_months_ago_open")
        assertThat(screenerItem.volume()).contains("25000000")
        assertThat(screenerItem.weekAvgVolume()).contains("22000000")
        assertThat(screenerItem.yearToDateOpen()).contains("year_to_date_open")
        assertThat(screenerItem.ytdChangePct()).contains("12.50")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val screenerItem =
            ScreenerItem.builder()
                .price("175.05")
                .securityId("AAPL")
                .securityIdSource(SecurityIdSource.CMS)
                .symbol("AAPL")
                .totalRatings(33)
                .consensusPriceTarget("200.00")
                .consensusRating(AnalystRating.STRONG_BUY)
                .countryOfIssue("US")
                .debtToEquityTtm("1.5")
                .description("Apple Inc. designs, manufactures, and markets smartphones...")
                .dividendYieldTtm("6.5")
                .earningsPerShareTtm("5.61")
                .exchange("XNMS")
                .fiftyTwoWeekHigh("230.00")
                .fiftyTwoWeekLow("165.00")
                .gapFrom52wHighPct("-8.50")
                .gapFrom52wLowPct("42.30")
                .industry("Consumer Electronics")
                .listDate(LocalDate.parse("1980-12-12"))
                .marketCap("2800000000000")
                .monthAvgVolume("23000000")
                .name("Apple Inc.")
                .oneMonthAgoClose("one_month_ago_close")
                .oneMonthAgoOpen("one_month_ago_open")
                .oneMonthChangePct("5.12")
                .oneWeekAgoClose("one_week_ago_close")
                .oneWeekAgoOpen("one_week_ago_open")
                .oneWeekChangePct("2.35")
                .oneYearAgoClose("one_year_ago_close")
                .oneYearAgoOpen("one_year_ago_open")
                .oneYearChangePct("one_year_change_pct")
                .percentChange("2.5")
                .prevDayClose("171.00")
                .priceToEarningsTtm("30.5")
                .sector("Technology")
                .securityType("COMMON_STOCK")
                .sixMonthChangePct("six_month_change_pct")
                .sixMonthsAgoClose("six_months_ago_close")
                .sixMonthsAgoOpen("six_months_ago_open")
                .threeMonthChangePct("three_month_change_pct")
                .threeMonthsAgoClose("three_months_ago_close")
                .threeMonthsAgoOpen("three_months_ago_open")
                .volume("25000000")
                .weekAvgVolume("22000000")
                .yearToDateOpen("year_to_date_open")
                .ytdChangePct("12.50")
                .build()

        val roundtrippedScreenerItem =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(screenerItem),
                jacksonTypeRef<ScreenerItem>(),
            )

        assertThat(roundtrippedScreenerItem).isEqualTo(screenerItem)
    }
}
