// File generated from our OpenAPI spec by Stainless.

package com.clear_street.api.models.active.v1.instruments.balancesheets

import com.clear_street.api.core.JsonValue
import com.clear_street.api.core.jsonMapper
import com.clear_street.api.models.ApiError
import com.clear_street.api.models.ResponseMetadata
import com.clear_street.api.models.active.v1.instruments.FiscalPeriodType
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BalanceSheetGetInstrumentBalanceSheetStatementsResponseTest {

    @Test
    fun create() {
        val balanceSheetGetInstrumentBalanceSheetStatementsResponse =
            BalanceSheetGetInstrumentBalanceSheetStatementsResponse.builder()
                .metadata(
                    ResponseMetadata.builder()
                        .requestId("request_id")
                        .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .pageNumber(0)
                        .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .totalItems(0L)
                        .totalPages(0)
                        .build()
                )
                .error(
                    ApiError.builder()
                        .code(400)
                        .message("Order quantity must be greater than zero")
                        .addDetail(
                            ApiError.Detail.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .addData(
                    InstrumentBalanceSheetStatement.builder()
                        .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                        .filingDate(LocalDate.parse("2025-05-01"))
                        .period("Q1")
                        .periodType(FiscalPeriodType.QUARTERLY)
                        .reportedCurrency("USD")
                        .year(2025)
                        .accountPayables("68960000000")
                        .accountsReceivables("accounts_receivables")
                        .accruedExpenses("accrued_expenses")
                        .accumulatedOtherComprehensiveIncomeLoss(
                            "accumulated_other_comprehensive_income_loss"
                        )
                        .additionalPaidInCapital("additional_paid_in_capital")
                        .capitalLeaseObligations("capital_lease_obligations")
                        .capitalLeaseObligationsCurrent("capital_lease_obligations_current")
                        .cashAndCashEquivalents("29943000000")
                        .cashAndShortTermInvestments("61533000000")
                        .commonStock("79850000000")
                        .deferredRevenue("deferred_revenue")
                        .deferredRevenueNonCurrent("deferred_revenue_non_current")
                        .deferredTaxLiabilitiesNonCurrent("deferred_tax_liabilities_non_current")
                        .goodwill("0")
                        .goodwillAndIntangibleAssets("goodwill_and_intangible_assets")
                        .intangibleAssets("0")
                        .inventory("6128000000")
                        .longTermDebt("95281000000")
                        .longTermInvestments("100544000000")
                        .minorityInterest("minority_interest")
                        .netDebt("76323000000")
                        .netReceivables("66243000000")
                        .otherAssets("other_assets")
                        .otherCurrentAssets("other_current_assets")
                        .otherCurrentLiabilities("other_current_liabilities")
                        .otherLiabilities("other_liabilities")
                        .otherNonCurrentAssets("other_non_current_assets")
                        .otherNonCurrentLiabilities("other_non_current_liabilities")
                        .otherPayables("other_payables")
                        .otherReceivables("other_receivables")
                        .otherTotalStockholdersEquity("other_total_stockholders_equity")
                        .preferredStock("preferred_stock")
                        .prepaids("prepaids")
                        .propertyPlantAndEquipmentNet("45336000000")
                        .retainedEarnings("-19154000000")
                        .shortTermDebt("10985000000")
                        .shortTermInvestments("31590000000")
                        .taxAssets("tax_assets")
                        .taxPayables("tax_payables")
                        .totalAssets("352583000000")
                        .totalCurrentAssets("143566000000")
                        .totalCurrentLiabilities("145308000000")
                        .totalDebt("106266000000")
                        .totalEquity("44325000000")
                        .totalInvestments("total_investments")
                        .totalLiabilities("308258000000")
                        .totalLiabilitiesAndTotalEquity("352583000000")
                        .totalNonCurrentAssets("209017000000")
                        .totalNonCurrentLiabilities("162950000000")
                        .totalPayables("total_payables")
                        .totalStockholdersEquity("56727000000")
                        .treasuryStock("treasury_stock")
                        .build()
                )
                .build()

        assertThat(balanceSheetGetInstrumentBalanceSheetStatementsResponse.metadata())
            .isEqualTo(
                ResponseMetadata.builder()
                    .requestId("request_id")
                    .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                    .pageNumber(0)
                    .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                    .totalItems(0L)
                    .totalPages(0)
                    .build()
            )
        assertThat(balanceSheetGetInstrumentBalanceSheetStatementsResponse.error())
            .contains(
                ApiError.builder()
                    .code(400)
                    .message("Order quantity must be greater than zero")
                    .addDetail(
                        ApiError.Detail.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(balanceSheetGetInstrumentBalanceSheetStatementsResponse.data())
            .containsExactly(
                InstrumentBalanceSheetStatement.builder()
                    .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                    .filingDate(LocalDate.parse("2025-05-01"))
                    .period("Q1")
                    .periodType(FiscalPeriodType.QUARTERLY)
                    .reportedCurrency("USD")
                    .year(2025)
                    .accountPayables("68960000000")
                    .accountsReceivables("accounts_receivables")
                    .accruedExpenses("accrued_expenses")
                    .accumulatedOtherComprehensiveIncomeLoss(
                        "accumulated_other_comprehensive_income_loss"
                    )
                    .additionalPaidInCapital("additional_paid_in_capital")
                    .capitalLeaseObligations("capital_lease_obligations")
                    .capitalLeaseObligationsCurrent("capital_lease_obligations_current")
                    .cashAndCashEquivalents("29943000000")
                    .cashAndShortTermInvestments("61533000000")
                    .commonStock("79850000000")
                    .deferredRevenue("deferred_revenue")
                    .deferredRevenueNonCurrent("deferred_revenue_non_current")
                    .deferredTaxLiabilitiesNonCurrent("deferred_tax_liabilities_non_current")
                    .goodwill("0")
                    .goodwillAndIntangibleAssets("goodwill_and_intangible_assets")
                    .intangibleAssets("0")
                    .inventory("6128000000")
                    .longTermDebt("95281000000")
                    .longTermInvestments("100544000000")
                    .minorityInterest("minority_interest")
                    .netDebt("76323000000")
                    .netReceivables("66243000000")
                    .otherAssets("other_assets")
                    .otherCurrentAssets("other_current_assets")
                    .otherCurrentLiabilities("other_current_liabilities")
                    .otherLiabilities("other_liabilities")
                    .otherNonCurrentAssets("other_non_current_assets")
                    .otherNonCurrentLiabilities("other_non_current_liabilities")
                    .otherPayables("other_payables")
                    .otherReceivables("other_receivables")
                    .otherTotalStockholdersEquity("other_total_stockholders_equity")
                    .preferredStock("preferred_stock")
                    .prepaids("prepaids")
                    .propertyPlantAndEquipmentNet("45336000000")
                    .retainedEarnings("-19154000000")
                    .shortTermDebt("10985000000")
                    .shortTermInvestments("31590000000")
                    .taxAssets("tax_assets")
                    .taxPayables("tax_payables")
                    .totalAssets("352583000000")
                    .totalCurrentAssets("143566000000")
                    .totalCurrentLiabilities("145308000000")
                    .totalDebt("106266000000")
                    .totalEquity("44325000000")
                    .totalInvestments("total_investments")
                    .totalLiabilities("308258000000")
                    .totalLiabilitiesAndTotalEquity("352583000000")
                    .totalNonCurrentAssets("209017000000")
                    .totalNonCurrentLiabilities("162950000000")
                    .totalPayables("total_payables")
                    .totalStockholdersEquity("56727000000")
                    .treasuryStock("treasury_stock")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val balanceSheetGetInstrumentBalanceSheetStatementsResponse =
            BalanceSheetGetInstrumentBalanceSheetStatementsResponse.builder()
                .metadata(
                    ResponseMetadata.builder()
                        .requestId("request_id")
                        .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .pageNumber(0)
                        .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .totalItems(0L)
                        .totalPages(0)
                        .build()
                )
                .error(
                    ApiError.builder()
                        .code(400)
                        .message("Order quantity must be greater than zero")
                        .addDetail(
                            ApiError.Detail.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .addData(
                    InstrumentBalanceSheetStatement.builder()
                        .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                        .filingDate(LocalDate.parse("2025-05-01"))
                        .period("Q1")
                        .periodType(FiscalPeriodType.QUARTERLY)
                        .reportedCurrency("USD")
                        .year(2025)
                        .accountPayables("68960000000")
                        .accountsReceivables("accounts_receivables")
                        .accruedExpenses("accrued_expenses")
                        .accumulatedOtherComprehensiveIncomeLoss(
                            "accumulated_other_comprehensive_income_loss"
                        )
                        .additionalPaidInCapital("additional_paid_in_capital")
                        .capitalLeaseObligations("capital_lease_obligations")
                        .capitalLeaseObligationsCurrent("capital_lease_obligations_current")
                        .cashAndCashEquivalents("29943000000")
                        .cashAndShortTermInvestments("61533000000")
                        .commonStock("79850000000")
                        .deferredRevenue("deferred_revenue")
                        .deferredRevenueNonCurrent("deferred_revenue_non_current")
                        .deferredTaxLiabilitiesNonCurrent("deferred_tax_liabilities_non_current")
                        .goodwill("0")
                        .goodwillAndIntangibleAssets("goodwill_and_intangible_assets")
                        .intangibleAssets("0")
                        .inventory("6128000000")
                        .longTermDebt("95281000000")
                        .longTermInvestments("100544000000")
                        .minorityInterest("minority_interest")
                        .netDebt("76323000000")
                        .netReceivables("66243000000")
                        .otherAssets("other_assets")
                        .otherCurrentAssets("other_current_assets")
                        .otherCurrentLiabilities("other_current_liabilities")
                        .otherLiabilities("other_liabilities")
                        .otherNonCurrentAssets("other_non_current_assets")
                        .otherNonCurrentLiabilities("other_non_current_liabilities")
                        .otherPayables("other_payables")
                        .otherReceivables("other_receivables")
                        .otherTotalStockholdersEquity("other_total_stockholders_equity")
                        .preferredStock("preferred_stock")
                        .prepaids("prepaids")
                        .propertyPlantAndEquipmentNet("45336000000")
                        .retainedEarnings("-19154000000")
                        .shortTermDebt("10985000000")
                        .shortTermInvestments("31590000000")
                        .taxAssets("tax_assets")
                        .taxPayables("tax_payables")
                        .totalAssets("352583000000")
                        .totalCurrentAssets("143566000000")
                        .totalCurrentLiabilities("145308000000")
                        .totalDebt("106266000000")
                        .totalEquity("44325000000")
                        .totalInvestments("total_investments")
                        .totalLiabilities("308258000000")
                        .totalLiabilitiesAndTotalEquity("352583000000")
                        .totalNonCurrentAssets("209017000000")
                        .totalNonCurrentLiabilities("162950000000")
                        .totalPayables("total_payables")
                        .totalStockholdersEquity("56727000000")
                        .treasuryStock("treasury_stock")
                        .build()
                )
                .build()

        val roundtrippedBalanceSheetGetInstrumentBalanceSheetStatementsResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(
                    balanceSheetGetInstrumentBalanceSheetStatementsResponse
                ),
                jacksonTypeRef<BalanceSheetGetInstrumentBalanceSheetStatementsResponse>(),
            )

        assertThat(roundtrippedBalanceSheetGetInstrumentBalanceSheetStatementsResponse)
            .isEqualTo(balanceSheetGetInstrumentBalanceSheetStatementsResponse)
    }
}
