// File generated from our OpenAPI spec by Stainless.

package com.clear_street.api.models.active.v1.instruments.balancesheets

import com.clear_street.api.core.jsonMapper
import com.clear_street.api.models.active.v1.instruments.FiscalPeriodType
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InstrumentBalanceSheetStatementTest {

    @Test
    fun create() {
        val instrumentBalanceSheetStatement =
            InstrumentBalanceSheetStatement.builder()
                .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                .filingDate(LocalDate.parse("2025-05-01"))
                .period("Q1")
                .periodType(FiscalPeriodType.QUARTERLY)
                .reportedCurrency("USD")
                .year(2025)
                .accountPayables("68960000000")
                .accountsReceivables("accounts_receivables")
                .accruedExpenses("accrued_expenses")
                .accumulatedOtherComprehensiveIncomeLoss(
                    "accumulated_other_comprehensive_income_loss"
                )
                .additionalPaidInCapital("additional_paid_in_capital")
                .capitalLeaseObligations("capital_lease_obligations")
                .capitalLeaseObligationsCurrent("capital_lease_obligations_current")
                .cashAndCashEquivalents("29943000000")
                .cashAndShortTermInvestments("61533000000")
                .commonStock("79850000000")
                .deferredRevenue("deferred_revenue")
                .deferredRevenueNonCurrent("deferred_revenue_non_current")
                .deferredTaxLiabilitiesNonCurrent("deferred_tax_liabilities_non_current")
                .goodwill("0")
                .goodwillAndIntangibleAssets("goodwill_and_intangible_assets")
                .intangibleAssets("0")
                .inventory("6128000000")
                .longTermDebt("95281000000")
                .longTermInvestments("100544000000")
                .minorityInterest("minority_interest")
                .netDebt("76323000000")
                .netReceivables("66243000000")
                .otherAssets("other_assets")
                .otherCurrentAssets("other_current_assets")
                .otherCurrentLiabilities("other_current_liabilities")
                .otherLiabilities("other_liabilities")
                .otherNonCurrentAssets("other_non_current_assets")
                .otherNonCurrentLiabilities("other_non_current_liabilities")
                .otherPayables("other_payables")
                .otherReceivables("other_receivables")
                .otherTotalStockholdersEquity("other_total_stockholders_equity")
                .preferredStock("preferred_stock")
                .prepaids("prepaids")
                .propertyPlantAndEquipmentNet("45336000000")
                .retainedEarnings("-19154000000")
                .shortTermDebt("10985000000")
                .shortTermInvestments("31590000000")
                .taxAssets("tax_assets")
                .taxPayables("tax_payables")
                .totalAssets("352583000000")
                .totalCurrentAssets("143566000000")
                .totalCurrentLiabilities("145308000000")
                .totalDebt("106266000000")
                .totalEquity("44325000000")
                .totalInvestments("total_investments")
                .totalLiabilities("308258000000")
                .totalLiabilitiesAndTotalEquity("352583000000")
                .totalNonCurrentAssets("209017000000")
                .totalNonCurrentLiabilities("162950000000")
                .totalPayables("total_payables")
                .totalStockholdersEquity("56727000000")
                .treasuryStock("treasury_stock")
                .build()

        assertThat(instrumentBalanceSheetStatement.acceptedDate())
            .isEqualTo(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
        assertThat(instrumentBalanceSheetStatement.filingDate())
            .isEqualTo(LocalDate.parse("2025-05-01"))
        assertThat(instrumentBalanceSheetStatement.period()).isEqualTo("Q1")
        assertThat(instrumentBalanceSheetStatement.periodType())
            .isEqualTo(FiscalPeriodType.QUARTERLY)
        assertThat(instrumentBalanceSheetStatement.reportedCurrency()).isEqualTo("USD")
        assertThat(instrumentBalanceSheetStatement.year()).isEqualTo(2025)
        assertThat(instrumentBalanceSheetStatement.accountPayables()).contains("68960000000")
        assertThat(instrumentBalanceSheetStatement.accountsReceivables())
            .contains("accounts_receivables")
        assertThat(instrumentBalanceSheetStatement.accruedExpenses()).contains("accrued_expenses")
        assertThat(instrumentBalanceSheetStatement.accumulatedOtherComprehensiveIncomeLoss())
            .contains("accumulated_other_comprehensive_income_loss")
        assertThat(instrumentBalanceSheetStatement.additionalPaidInCapital())
            .contains("additional_paid_in_capital")
        assertThat(instrumentBalanceSheetStatement.capitalLeaseObligations())
            .contains("capital_lease_obligations")
        assertThat(instrumentBalanceSheetStatement.capitalLeaseObligationsCurrent())
            .contains("capital_lease_obligations_current")
        assertThat(instrumentBalanceSheetStatement.cashAndCashEquivalents()).contains("29943000000")
        assertThat(instrumentBalanceSheetStatement.cashAndShortTermInvestments())
            .contains("61533000000")
        assertThat(instrumentBalanceSheetStatement.commonStock()).contains("79850000000")
        assertThat(instrumentBalanceSheetStatement.deferredRevenue()).contains("deferred_revenue")
        assertThat(instrumentBalanceSheetStatement.deferredRevenueNonCurrent())
            .contains("deferred_revenue_non_current")
        assertThat(instrumentBalanceSheetStatement.deferredTaxLiabilitiesNonCurrent())
            .contains("deferred_tax_liabilities_non_current")
        assertThat(instrumentBalanceSheetStatement.goodwill()).contains("0")
        assertThat(instrumentBalanceSheetStatement.goodwillAndIntangibleAssets())
            .contains("goodwill_and_intangible_assets")
        assertThat(instrumentBalanceSheetStatement.intangibleAssets()).contains("0")
        assertThat(instrumentBalanceSheetStatement.inventory()).contains("6128000000")
        assertThat(instrumentBalanceSheetStatement.longTermDebt()).contains("95281000000")
        assertThat(instrumentBalanceSheetStatement.longTermInvestments()).contains("100544000000")
        assertThat(instrumentBalanceSheetStatement.minorityInterest()).contains("minority_interest")
        assertThat(instrumentBalanceSheetStatement.netDebt()).contains("76323000000")
        assertThat(instrumentBalanceSheetStatement.netReceivables()).contains("66243000000")
        assertThat(instrumentBalanceSheetStatement.otherAssets()).contains("other_assets")
        assertThat(instrumentBalanceSheetStatement.otherCurrentAssets())
            .contains("other_current_assets")
        assertThat(instrumentBalanceSheetStatement.otherCurrentLiabilities())
            .contains("other_current_liabilities")
        assertThat(instrumentBalanceSheetStatement.otherLiabilities()).contains("other_liabilities")
        assertThat(instrumentBalanceSheetStatement.otherNonCurrentAssets())
            .contains("other_non_current_assets")
        assertThat(instrumentBalanceSheetStatement.otherNonCurrentLiabilities())
            .contains("other_non_current_liabilities")
        assertThat(instrumentBalanceSheetStatement.otherPayables()).contains("other_payables")
        assertThat(instrumentBalanceSheetStatement.otherReceivables()).contains("other_receivables")
        assertThat(instrumentBalanceSheetStatement.otherTotalStockholdersEquity())
            .contains("other_total_stockholders_equity")
        assertThat(instrumentBalanceSheetStatement.preferredStock()).contains("preferred_stock")
        assertThat(instrumentBalanceSheetStatement.prepaids()).contains("prepaids")
        assertThat(instrumentBalanceSheetStatement.propertyPlantAndEquipmentNet())
            .contains("45336000000")
        assertThat(instrumentBalanceSheetStatement.retainedEarnings()).contains("-19154000000")
        assertThat(instrumentBalanceSheetStatement.shortTermDebt()).contains("10985000000")
        assertThat(instrumentBalanceSheetStatement.shortTermInvestments()).contains("31590000000")
        assertThat(instrumentBalanceSheetStatement.taxAssets()).contains("tax_assets")
        assertThat(instrumentBalanceSheetStatement.taxPayables()).contains("tax_payables")
        assertThat(instrumentBalanceSheetStatement.totalAssets()).contains("352583000000")
        assertThat(instrumentBalanceSheetStatement.totalCurrentAssets()).contains("143566000000")
        assertThat(instrumentBalanceSheetStatement.totalCurrentLiabilities())
            .contains("145308000000")
        assertThat(instrumentBalanceSheetStatement.totalDebt()).contains("106266000000")
        assertThat(instrumentBalanceSheetStatement.totalEquity()).contains("44325000000")
        assertThat(instrumentBalanceSheetStatement.totalInvestments()).contains("total_investments")
        assertThat(instrumentBalanceSheetStatement.totalLiabilities()).contains("308258000000")
        assertThat(instrumentBalanceSheetStatement.totalLiabilitiesAndTotalEquity())
            .contains("352583000000")
        assertThat(instrumentBalanceSheetStatement.totalNonCurrentAssets()).contains("209017000000")
        assertThat(instrumentBalanceSheetStatement.totalNonCurrentLiabilities())
            .contains("162950000000")
        assertThat(instrumentBalanceSheetStatement.totalPayables()).contains("total_payables")
        assertThat(instrumentBalanceSheetStatement.totalStockholdersEquity())
            .contains("56727000000")
        assertThat(instrumentBalanceSheetStatement.treasuryStock()).contains("treasury_stock")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val instrumentBalanceSheetStatement =
            InstrumentBalanceSheetStatement.builder()
                .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                .filingDate(LocalDate.parse("2025-05-01"))
                .period("Q1")
                .periodType(FiscalPeriodType.QUARTERLY)
                .reportedCurrency("USD")
                .year(2025)
                .accountPayables("68960000000")
                .accountsReceivables("accounts_receivables")
                .accruedExpenses("accrued_expenses")
                .accumulatedOtherComprehensiveIncomeLoss(
                    "accumulated_other_comprehensive_income_loss"
                )
                .additionalPaidInCapital("additional_paid_in_capital")
                .capitalLeaseObligations("capital_lease_obligations")
                .capitalLeaseObligationsCurrent("capital_lease_obligations_current")
                .cashAndCashEquivalents("29943000000")
                .cashAndShortTermInvestments("61533000000")
                .commonStock("79850000000")
                .deferredRevenue("deferred_revenue")
                .deferredRevenueNonCurrent("deferred_revenue_non_current")
                .deferredTaxLiabilitiesNonCurrent("deferred_tax_liabilities_non_current")
                .goodwill("0")
                .goodwillAndIntangibleAssets("goodwill_and_intangible_assets")
                .intangibleAssets("0")
                .inventory("6128000000")
                .longTermDebt("95281000000")
                .longTermInvestments("100544000000")
                .minorityInterest("minority_interest")
                .netDebt("76323000000")
                .netReceivables("66243000000")
                .otherAssets("other_assets")
                .otherCurrentAssets("other_current_assets")
                .otherCurrentLiabilities("other_current_liabilities")
                .otherLiabilities("other_liabilities")
                .otherNonCurrentAssets("other_non_current_assets")
                .otherNonCurrentLiabilities("other_non_current_liabilities")
                .otherPayables("other_payables")
                .otherReceivables("other_receivables")
                .otherTotalStockholdersEquity("other_total_stockholders_equity")
                .preferredStock("preferred_stock")
                .prepaids("prepaids")
                .propertyPlantAndEquipmentNet("45336000000")
                .retainedEarnings("-19154000000")
                .shortTermDebt("10985000000")
                .shortTermInvestments("31590000000")
                .taxAssets("tax_assets")
                .taxPayables("tax_payables")
                .totalAssets("352583000000")
                .totalCurrentAssets("143566000000")
                .totalCurrentLiabilities("145308000000")
                .totalDebt("106266000000")
                .totalEquity("44325000000")
                .totalInvestments("total_investments")
                .totalLiabilities("308258000000")
                .totalLiabilitiesAndTotalEquity("352583000000")
                .totalNonCurrentAssets("209017000000")
                .totalNonCurrentLiabilities("162950000000")
                .totalPayables("total_payables")
                .totalStockholdersEquity("56727000000")
                .treasuryStock("treasury_stock")
                .build()

        val roundtrippedInstrumentBalanceSheetStatement =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(instrumentBalanceSheetStatement),
                jacksonTypeRef<InstrumentBalanceSheetStatement>(),
            )

        assertThat(roundtrippedInstrumentBalanceSheetStatement)
            .isEqualTo(instrumentBalanceSheetStatement)
    }
}
