// File generated from our OpenAPI spec by Stainless.

package com.clearstreet.api.models.v1.privatemarkets.companies

import com.clearstreet.api.core.JsonValue
import com.clearstreet.api.core.jsonMapper
import com.clearstreet.api.models.v1.privatemarkets.offerings.MetricUnit
import com.clearstreet.api.models.v1.privatemarkets.offerings.MetricValueType
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CompanyDetailTest {

    @Test
    fun create() {
        val companyDetail =
            CompanyDetail.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .name("name")
                .profile(
                    CompanyProfileResource.builder()
                        .addCategory(CompanyCategory.builder().name("name").slug("slug").build())
                        .addCitation(
                            CompanyCitation.builder()
                                .id("id")
                                .source("source")
                                .title("title")
                                .url("url")
                                .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .addCustomer(
                            CompanyCustomer.builder().name("name").logoUrl("logo_url").build()
                        )
                        .addDocument(
                            CompanyDocumentResource.builder()
                                .documentType(CompanyDocumentType.COMPANY_PROFILE)
                                .relation(CompanyDocumentRelation.SUBJECT)
                                .title("title")
                                .url("url")
                                .externalId("external_id")
                                .preview(
                                    CompanyDocumentPreview.builder()
                                        .description("description")
                                        .imageUrl("image_url")
                                        .build()
                                )
                                .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .headquarters(
                            CompanyHeadquarters.builder().city("city").country("country").build()
                        )
                        .addLegalEntity(
                            CompanyLegalEntity.builder().country("country").name("name").build()
                        )
                        .addMetricSeries(
                            CompanyMetricSeries.builder()
                                .frequency(MetricFrequency.YEAR)
                                .label("label")
                                .metricKey(MetricKey.ANNUALIZED_REVENUE)
                                .source("source")
                                .unit(MetricUnit.USD)
                                .externalId("external_id")
                                .addPoint(
                                    CompanyMetricPoint.builder()
                                        .observedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .value("0.42")
                                        .valueType(MetricValueType.HISTORICAL)
                                        .addCitationId("string")
                                        .sourceEventId("source_event_id")
                                        .sourceMetadata(
                                            CompanyMetricPoint.SourceMetadata.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .sourceUrl("source_url")
                                .build()
                        )
                        .addNarrativeSection(
                            CompanyNarrativeSection.builder()
                                .body("body")
                                .displayOrder(0)
                                .title("title")
                                .addCitationId("string")
                                .build()
                        )
                        .overview("overview")
                        .addPerson(
                            CompanyPerson.builder()
                                .name("name")
                                .externalId("external_id")
                                .addRole(CompanyPersonRole.FOUNDER)
                                .build()
                        )
                        .addSocial(
                            CompanySocialLink.builder()
                                .type(CompanySocialType.WEBSITE)
                                .url("url")
                                .build()
                        )
                        .tagline("tagline")
                        .build()
                )
                .profileSchemaVersion(0)
                .shortDescription("short_description")
                .slug("slug")
                .logoUrl("logo_url")
                .primaryDomain("primary_domain")
                .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(companyDetail.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(companyDetail.name()).isEqualTo("name")
        assertThat(companyDetail.profile())
            .isEqualTo(
                CompanyProfileResource.builder()
                    .addCategory(CompanyCategory.builder().name("name").slug("slug").build())
                    .addCitation(
                        CompanyCitation.builder()
                            .id("id")
                            .source("source")
                            .title("title")
                            .url("url")
                            .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .addCustomer(CompanyCustomer.builder().name("name").logoUrl("logo_url").build())
                    .addDocument(
                        CompanyDocumentResource.builder()
                            .documentType(CompanyDocumentType.COMPANY_PROFILE)
                            .relation(CompanyDocumentRelation.SUBJECT)
                            .title("title")
                            .url("url")
                            .externalId("external_id")
                            .preview(
                                CompanyDocumentPreview.builder()
                                    .description("description")
                                    .imageUrl("image_url")
                                    .build()
                            )
                            .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .headquarters(
                        CompanyHeadquarters.builder().city("city").country("country").build()
                    )
                    .addLegalEntity(
                        CompanyLegalEntity.builder().country("country").name("name").build()
                    )
                    .addMetricSeries(
                        CompanyMetricSeries.builder()
                            .frequency(MetricFrequency.YEAR)
                            .label("label")
                            .metricKey(MetricKey.ANNUALIZED_REVENUE)
                            .source("source")
                            .unit(MetricUnit.USD)
                            .externalId("external_id")
                            .addPoint(
                                CompanyMetricPoint.builder()
                                    .observedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .value("0.42")
                                    .valueType(MetricValueType.HISTORICAL)
                                    .addCitationId("string")
                                    .sourceEventId("source_event_id")
                                    .sourceMetadata(
                                        CompanyMetricPoint.SourceMetadata.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .build()
                            )
                            .sourceUrl("source_url")
                            .build()
                    )
                    .addNarrativeSection(
                        CompanyNarrativeSection.builder()
                            .body("body")
                            .displayOrder(0)
                            .title("title")
                            .addCitationId("string")
                            .build()
                    )
                    .overview("overview")
                    .addPerson(
                        CompanyPerson.builder()
                            .name("name")
                            .externalId("external_id")
                            .addRole(CompanyPersonRole.FOUNDER)
                            .build()
                    )
                    .addSocial(
                        CompanySocialLink.builder()
                            .type(CompanySocialType.WEBSITE)
                            .url("url")
                            .build()
                    )
                    .tagline("tagline")
                    .build()
            )
        assertThat(companyDetail.profileSchemaVersion()).isEqualTo(0)
        assertThat(companyDetail.shortDescription()).isEqualTo("short_description")
        assertThat(companyDetail.slug()).isEqualTo("slug")
        assertThat(companyDetail.logoUrl()).contains("logo_url")
        assertThat(companyDetail.primaryDomain()).contains("primary_domain")
        assertThat(companyDetail.publishedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val companyDetail =
            CompanyDetail.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .name("name")
                .profile(
                    CompanyProfileResource.builder()
                        .addCategory(CompanyCategory.builder().name("name").slug("slug").build())
                        .addCitation(
                            CompanyCitation.builder()
                                .id("id")
                                .source("source")
                                .title("title")
                                .url("url")
                                .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .addCustomer(
                            CompanyCustomer.builder().name("name").logoUrl("logo_url").build()
                        )
                        .addDocument(
                            CompanyDocumentResource.builder()
                                .documentType(CompanyDocumentType.COMPANY_PROFILE)
                                .relation(CompanyDocumentRelation.SUBJECT)
                                .title("title")
                                .url("url")
                                .externalId("external_id")
                                .preview(
                                    CompanyDocumentPreview.builder()
                                        .description("description")
                                        .imageUrl("image_url")
                                        .build()
                                )
                                .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .headquarters(
                            CompanyHeadquarters.builder().city("city").country("country").build()
                        )
                        .addLegalEntity(
                            CompanyLegalEntity.builder().country("country").name("name").build()
                        )
                        .addMetricSeries(
                            CompanyMetricSeries.builder()
                                .frequency(MetricFrequency.YEAR)
                                .label("label")
                                .metricKey(MetricKey.ANNUALIZED_REVENUE)
                                .source("source")
                                .unit(MetricUnit.USD)
                                .externalId("external_id")
                                .addPoint(
                                    CompanyMetricPoint.builder()
                                        .observedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .value("0.42")
                                        .valueType(MetricValueType.HISTORICAL)
                                        .addCitationId("string")
                                        .sourceEventId("source_event_id")
                                        .sourceMetadata(
                                            CompanyMetricPoint.SourceMetadata.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .sourceUrl("source_url")
                                .build()
                        )
                        .addNarrativeSection(
                            CompanyNarrativeSection.builder()
                                .body("body")
                                .displayOrder(0)
                                .title("title")
                                .addCitationId("string")
                                .build()
                        )
                        .overview("overview")
                        .addPerson(
                            CompanyPerson.builder()
                                .name("name")
                                .externalId("external_id")
                                .addRole(CompanyPersonRole.FOUNDER)
                                .build()
                        )
                        .addSocial(
                            CompanySocialLink.builder()
                                .type(CompanySocialType.WEBSITE)
                                .url("url")
                                .build()
                        )
                        .tagline("tagline")
                        .build()
                )
                .profileSchemaVersion(0)
                .shortDescription("short_description")
                .slug("slug")
                .logoUrl("logo_url")
                .primaryDomain("primary_domain")
                .publishedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedCompanyDetail =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(companyDetail),
                jacksonTypeRef<CompanyDetail>(),
            )

        assertThat(roundtrippedCompanyDetail).isEqualTo(companyDetail)
    }
}
