// File generated from our OpenAPI spec by Stainless.

package com.clear_street.api.models.v1.screener

import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ScreenerSearchScreenerParamsTest {

    @Test
    fun create() {
        ScreenerSearchScreenerParams.builder()
            .fieldFilter(
                listOf(
                    FieldRef.builder()
                        .name("market_cap")
                        .lookback(FieldLookback.ONE_WEEK)
                        .period(FieldPeriod.QUARTER)
                        .valueType(FieldType.DECIMAL)
                        .build(),
                    FieldRef.builder()
                        .name("price")
                        .lookback(FieldLookback.ONE_WEEK)
                        .period(FieldPeriod.QUARTER)
                        .valueType(FieldType.DECIMAL)
                        .build(),
                    FieldRef.builder()
                        .name("volume")
                        .lookback(FieldLookback.ONE_WEEK)
                        .period(FieldPeriod.QUARTER)
                        .valueType(FieldType.DECIMAL)
                        .build(),
                )
            )
            .addFilter(
                SearchFilter.builder()
                    .left(
                        FieldRef.builder()
                            .name("market_cap")
                            .lookback(FieldLookback.ONE_WEEK)
                            .period(FieldPeriod.QUARTER)
                            .valueType(FieldType.DECIMAL)
                            .build()
                    )
                    .op(
                        FilterOpSpec.builder()
                            .name(FilterOperator.GTE)
                            .addArg(OperatorArg.LEFT_INCLUSIVE)
                            .build()
                    )
                    .addRight(
                        FilterValue.builder()
                            .value(1000000000.0)
                            .variable(
                                Variable.builder()
                                    .name("today")
                                    .lookback(FieldLookback.ONE_WEEK)
                                    .modifier(
                                        Modifier.builder()
                                            .addArg(30.0)
                                            .addArg("DAY")
                                            .name(ModifierOp.SUB)
                                            .build()
                                    )
                                    .period(FieldPeriod.QUARTER)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .pageSize(25L)
            .pageToken("page_token")
            .sortBy(
                FieldRef.builder()
                    .name("market_cap")
                    .lookback(FieldLookback.ONE_WEEK)
                    .period(FieldPeriod.QUARTER)
                    .valueType(FieldType.DECIMAL)
                    .build()
            )
            .sortCaseSensitive(true)
            .sortDirection(ScreenerSearchScreenerParams.SortDirection.ASC)
            .addSort(
                ScreenerSearchScreenerParams.Sort.builder()
                    .field(
                        FieldRef.builder()
                            .name("market_cap")
                            .lookback(FieldLookback.ONE_WEEK)
                            .period(FieldPeriod.QUARTER)
                            .valueType(FieldType.DECIMAL)
                            .build()
                    )
                    .direction(ScreenerSearchScreenerParams.Sort.Direction.DESC)
                    .build()
            )
            .build()
    }

    @Test
    fun body() {
        val params =
            ScreenerSearchScreenerParams.builder()
                .fieldFilter(
                    listOf(
                        FieldRef.builder()
                            .name("market_cap")
                            .lookback(FieldLookback.ONE_WEEK)
                            .period(FieldPeriod.QUARTER)
                            .valueType(FieldType.DECIMAL)
                            .build(),
                        FieldRef.builder()
                            .name("price")
                            .lookback(FieldLookback.ONE_WEEK)
                            .period(FieldPeriod.QUARTER)
                            .valueType(FieldType.DECIMAL)
                            .build(),
                        FieldRef.builder()
                            .name("volume")
                            .lookback(FieldLookback.ONE_WEEK)
                            .period(FieldPeriod.QUARTER)
                            .valueType(FieldType.DECIMAL)
                            .build(),
                    )
                )
                .addFilter(
                    SearchFilter.builder()
                        .left(
                            FieldRef.builder()
                                .name("market_cap")
                                .lookback(FieldLookback.ONE_WEEK)
                                .period(FieldPeriod.QUARTER)
                                .valueType(FieldType.DECIMAL)
                                .build()
                        )
                        .op(
                            FilterOpSpec.builder()
                                .name(FilterOperator.GTE)
                                .addArg(OperatorArg.LEFT_INCLUSIVE)
                                .build()
                        )
                        .addRight(
                            FilterValue.builder()
                                .value(1000000000.0)
                                .variable(
                                    Variable.builder()
                                        .name("today")
                                        .lookback(FieldLookback.ONE_WEEK)
                                        .modifier(
                                            Modifier.builder()
                                                .addArg(30.0)
                                                .addArg("DAY")
                                                .name(ModifierOp.SUB)
                                                .build()
                                        )
                                        .period(FieldPeriod.QUARTER)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .pageSize(25L)
                .pageToken("page_token")
                .sortBy(
                    FieldRef.builder()
                        .name("market_cap")
                        .lookback(FieldLookback.ONE_WEEK)
                        .period(FieldPeriod.QUARTER)
                        .valueType(FieldType.DECIMAL)
                        .build()
                )
                .sortCaseSensitive(true)
                .sortDirection(ScreenerSearchScreenerParams.SortDirection.ASC)
                .addSort(
                    ScreenerSearchScreenerParams.Sort.builder()
                        .field(
                            FieldRef.builder()
                                .name("market_cap")
                                .lookback(FieldLookback.ONE_WEEK)
                                .period(FieldPeriod.QUARTER)
                                .valueType(FieldType.DECIMAL)
                                .build()
                        )
                        .direction(ScreenerSearchScreenerParams.Sort.Direction.DESC)
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.fieldFilter().getOrNull())
            .containsExactly(
                FieldRef.builder()
                    .name("market_cap")
                    .lookback(FieldLookback.ONE_WEEK)
                    .period(FieldPeriod.QUARTER)
                    .valueType(FieldType.DECIMAL)
                    .build(),
                FieldRef.builder()
                    .name("price")
                    .lookback(FieldLookback.ONE_WEEK)
                    .period(FieldPeriod.QUARTER)
                    .valueType(FieldType.DECIMAL)
                    .build(),
                FieldRef.builder()
                    .name("volume")
                    .lookback(FieldLookback.ONE_WEEK)
                    .period(FieldPeriod.QUARTER)
                    .valueType(FieldType.DECIMAL)
                    .build(),
            )
        assertThat(body.filters().getOrNull())
            .containsExactly(
                SearchFilter.builder()
                    .left(
                        FieldRef.builder()
                            .name("market_cap")
                            .lookback(FieldLookback.ONE_WEEK)
                            .period(FieldPeriod.QUARTER)
                            .valueType(FieldType.DECIMAL)
                            .build()
                    )
                    .op(
                        FilterOpSpec.builder()
                            .name(FilterOperator.GTE)
                            .addArg(OperatorArg.LEFT_INCLUSIVE)
                            .build()
                    )
                    .addRight(
                        FilterValue.builder()
                            .value(1000000000.0)
                            .variable(
                                Variable.builder()
                                    .name("today")
                                    .lookback(FieldLookback.ONE_WEEK)
                                    .modifier(
                                        Modifier.builder()
                                            .addArg(30.0)
                                            .addArg("DAY")
                                            .name(ModifierOp.SUB)
                                            .build()
                                    )
                                    .period(FieldPeriod.QUARTER)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.pageSize()).contains(25L)
        assertThat(body.pageToken()).contains("page_token")
        assertThat(body.sortBy())
            .contains(
                FieldRef.builder()
                    .name("market_cap")
                    .lookback(FieldLookback.ONE_WEEK)
                    .period(FieldPeriod.QUARTER)
                    .valueType(FieldType.DECIMAL)
                    .build()
            )
        assertThat(body.sortCaseSensitive()).contains(true)
        assertThat(body.sortDirection()).contains(ScreenerSearchScreenerParams.SortDirection.ASC)
        assertThat(body.sorts().getOrNull())
            .containsExactly(
                ScreenerSearchScreenerParams.Sort.builder()
                    .field(
                        FieldRef.builder()
                            .name("market_cap")
                            .lookback(FieldLookback.ONE_WEEK)
                            .period(FieldPeriod.QUARTER)
                            .valueType(FieldType.DECIMAL)
                            .build()
                    )
                    .direction(ScreenerSearchScreenerParams.Sort.Direction.DESC)
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = ScreenerSearchScreenerParams.builder().build()

        val body = params._body()
    }
}
