// File generated from our OpenAPI spec by Stainless.

package com.clear_street.api.models.v1.instruments.cashflowstatements

import com.clear_street.api.core.jsonMapper
import com.clear_street.api.models.v1.instruments.FiscalPeriodType
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InstrumentCashFlowStatementTest {

    @Test
    fun create() {
        val instrumentCashFlowStatement =
            InstrumentCashFlowStatement.builder()
                .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                .filingDate(LocalDate.parse("2025-05-01"))
                .period("Q1")
                .periodType(FiscalPeriodType.QUARTERLY)
                .reportedCurrency("USD")
                .year(2025)
                .accountsPayables("accounts_payables")
                .accountsReceivables("accounts_receivables")
                .acquisitionsNet("acquisitions_net")
                .capitalExpenditure("-2600000000")
                .cashAtBeginningOfPeriod("33743000000")
                .cashAtEndOfPeriod("29943000000")
                .changeInWorkingCapital("-3200000000")
                .commonDividendsPaid("common_dividends_paid")
                .commonStockIssuance("common_stock_issuance")
                .commonStockRepurchased("-23000000000")
                .deferredIncomeTax("deferred_income_tax")
                .depreciationAndAmortization("2900000000")
                .effectOfForexChangesOnCash("effect_of_forex_changes_on_cash")
                .freeCashFlow("25800000000")
                .incomeTaxesPaid("income_taxes_paid")
                .interestPaid("interest_paid")
                .inventory("inventory")
                .investmentsInPropertyPlantAndEquipment("-2600000000")
                .longTermNetDebtIssuance("long_term_net_debt_issuance")
                .netCashProvidedByFinancingActivities("-28300000000")
                .netCashProvidedByInvestingActivities("-3900000000")
                .netCashProvidedByOperatingActivities("28400000000")
                .netChangeInCash("-3800000000")
                .netCommonStockIssuance("net_common_stock_issuance")
                .netDebtIssuance("-1500000000")
                .netDividendsPaid("-3800000000")
                .netIncome("22200000000")
                .netPreferredStockIssuance("net_preferred_stock_issuance")
                .netStockIssuance("net_stock_issuance")
                .operatingCashFlow("28400000000")
                .otherFinancingActivities("other_financing_activities")
                .otherInvestingActivities("other_investing_activities")
                .otherNonCashItems("other_non_cash_items")
                .otherWorkingCapital("other_working_capital")
                .preferredDividendsPaid("preferred_dividends_paid")
                .purchasesOfInvestments("-9500000000")
                .salesMaturitiesOfInvestments("8200000000")
                .shortTermNetDebtIssuance("short_term_net_debt_issuance")
                .stockBasedCompensation("2500000000")
                .build()

        assertThat(instrumentCashFlowStatement.acceptedDate())
            .isEqualTo(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
        assertThat(instrumentCashFlowStatement.filingDate())
            .isEqualTo(LocalDate.parse("2025-05-01"))
        assertThat(instrumentCashFlowStatement.period()).isEqualTo("Q1")
        assertThat(instrumentCashFlowStatement.periodType()).isEqualTo(FiscalPeriodType.QUARTERLY)
        assertThat(instrumentCashFlowStatement.reportedCurrency()).isEqualTo("USD")
        assertThat(instrumentCashFlowStatement.year()).isEqualTo(2025)
        assertThat(instrumentCashFlowStatement.accountsPayables()).contains("accounts_payables")
        assertThat(instrumentCashFlowStatement.accountsReceivables())
            .contains("accounts_receivables")
        assertThat(instrumentCashFlowStatement.acquisitionsNet()).contains("acquisitions_net")
        assertThat(instrumentCashFlowStatement.capitalExpenditure()).contains("-2600000000")
        assertThat(instrumentCashFlowStatement.cashAtBeginningOfPeriod()).contains("33743000000")
        assertThat(instrumentCashFlowStatement.cashAtEndOfPeriod()).contains("29943000000")
        assertThat(instrumentCashFlowStatement.changeInWorkingCapital()).contains("-3200000000")
        assertThat(instrumentCashFlowStatement.commonDividendsPaid())
            .contains("common_dividends_paid")
        assertThat(instrumentCashFlowStatement.commonStockIssuance())
            .contains("common_stock_issuance")
        assertThat(instrumentCashFlowStatement.commonStockRepurchased()).contains("-23000000000")
        assertThat(instrumentCashFlowStatement.deferredIncomeTax()).contains("deferred_income_tax")
        assertThat(instrumentCashFlowStatement.depreciationAndAmortization()).contains("2900000000")
        assertThat(instrumentCashFlowStatement.effectOfForexChangesOnCash())
            .contains("effect_of_forex_changes_on_cash")
        assertThat(instrumentCashFlowStatement.freeCashFlow()).contains("25800000000")
        assertThat(instrumentCashFlowStatement.incomeTaxesPaid()).contains("income_taxes_paid")
        assertThat(instrumentCashFlowStatement.interestPaid()).contains("interest_paid")
        assertThat(instrumentCashFlowStatement.inventory()).contains("inventory")
        assertThat(instrumentCashFlowStatement.investmentsInPropertyPlantAndEquipment())
            .contains("-2600000000")
        assertThat(instrumentCashFlowStatement.longTermNetDebtIssuance())
            .contains("long_term_net_debt_issuance")
        assertThat(instrumentCashFlowStatement.netCashProvidedByFinancingActivities())
            .contains("-28300000000")
        assertThat(instrumentCashFlowStatement.netCashProvidedByInvestingActivities())
            .contains("-3900000000")
        assertThat(instrumentCashFlowStatement.netCashProvidedByOperatingActivities())
            .contains("28400000000")
        assertThat(instrumentCashFlowStatement.netChangeInCash()).contains("-3800000000")
        assertThat(instrumentCashFlowStatement.netCommonStockIssuance())
            .contains("net_common_stock_issuance")
        assertThat(instrumentCashFlowStatement.netDebtIssuance()).contains("-1500000000")
        assertThat(instrumentCashFlowStatement.netDividendsPaid()).contains("-3800000000")
        assertThat(instrumentCashFlowStatement.netIncome()).contains("22200000000")
        assertThat(instrumentCashFlowStatement.netPreferredStockIssuance())
            .contains("net_preferred_stock_issuance")
        assertThat(instrumentCashFlowStatement.netStockIssuance()).contains("net_stock_issuance")
        assertThat(instrumentCashFlowStatement.operatingCashFlow()).contains("28400000000")
        assertThat(instrumentCashFlowStatement.otherFinancingActivities())
            .contains("other_financing_activities")
        assertThat(instrumentCashFlowStatement.otherInvestingActivities())
            .contains("other_investing_activities")
        assertThat(instrumentCashFlowStatement.otherNonCashItems()).contains("other_non_cash_items")
        assertThat(instrumentCashFlowStatement.otherWorkingCapital())
            .contains("other_working_capital")
        assertThat(instrumentCashFlowStatement.preferredDividendsPaid())
            .contains("preferred_dividends_paid")
        assertThat(instrumentCashFlowStatement.purchasesOfInvestments()).contains("-9500000000")
        assertThat(instrumentCashFlowStatement.salesMaturitiesOfInvestments())
            .contains("8200000000")
        assertThat(instrumentCashFlowStatement.shortTermNetDebtIssuance())
            .contains("short_term_net_debt_issuance")
        assertThat(instrumentCashFlowStatement.stockBasedCompensation()).contains("2500000000")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val instrumentCashFlowStatement =
            InstrumentCashFlowStatement.builder()
                .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                .filingDate(LocalDate.parse("2025-05-01"))
                .period("Q1")
                .periodType(FiscalPeriodType.QUARTERLY)
                .reportedCurrency("USD")
                .year(2025)
                .accountsPayables("accounts_payables")
                .accountsReceivables("accounts_receivables")
                .acquisitionsNet("acquisitions_net")
                .capitalExpenditure("-2600000000")
                .cashAtBeginningOfPeriod("33743000000")
                .cashAtEndOfPeriod("29943000000")
                .changeInWorkingCapital("-3200000000")
                .commonDividendsPaid("common_dividends_paid")
                .commonStockIssuance("common_stock_issuance")
                .commonStockRepurchased("-23000000000")
                .deferredIncomeTax("deferred_income_tax")
                .depreciationAndAmortization("2900000000")
                .effectOfForexChangesOnCash("effect_of_forex_changes_on_cash")
                .freeCashFlow("25800000000")
                .incomeTaxesPaid("income_taxes_paid")
                .interestPaid("interest_paid")
                .inventory("inventory")
                .investmentsInPropertyPlantAndEquipment("-2600000000")
                .longTermNetDebtIssuance("long_term_net_debt_issuance")
                .netCashProvidedByFinancingActivities("-28300000000")
                .netCashProvidedByInvestingActivities("-3900000000")
                .netCashProvidedByOperatingActivities("28400000000")
                .netChangeInCash("-3800000000")
                .netCommonStockIssuance("net_common_stock_issuance")
                .netDebtIssuance("-1500000000")
                .netDividendsPaid("-3800000000")
                .netIncome("22200000000")
                .netPreferredStockIssuance("net_preferred_stock_issuance")
                .netStockIssuance("net_stock_issuance")
                .operatingCashFlow("28400000000")
                .otherFinancingActivities("other_financing_activities")
                .otherInvestingActivities("other_investing_activities")
                .otherNonCashItems("other_non_cash_items")
                .otherWorkingCapital("other_working_capital")
                .preferredDividendsPaid("preferred_dividends_paid")
                .purchasesOfInvestments("-9500000000")
                .salesMaturitiesOfInvestments("8200000000")
                .shortTermNetDebtIssuance("short_term_net_debt_issuance")
                .stockBasedCompensation("2500000000")
                .build()

        val roundtrippedInstrumentCashFlowStatement =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(instrumentCashFlowStatement),
                jacksonTypeRef<InstrumentCashFlowStatement>(),
            )

        assertThat(roundtrippedInstrumentCashFlowStatement).isEqualTo(instrumentCashFlowStatement)
    }
}
