// File generated from our OpenAPI spec by Stainless.

package com.clear_street.api.models.active.v1.instruments.cashflowstatements

import com.clear_street.api.core.JsonValue
import com.clear_street.api.core.jsonMapper
import com.clear_street.api.models.ApiError
import com.clear_street.api.models.ResponseMetadata
import com.clear_street.api.models.active.v1.instruments.FiscalPeriodType
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CashFlowStatementGetInstrumentCashFlowStatementsResponseTest {

    @Test
    fun create() {
        val cashFlowStatementGetInstrumentCashFlowStatementsResponse =
            CashFlowStatementGetInstrumentCashFlowStatementsResponse.builder()
                .metadata(
                    ResponseMetadata.builder()
                        .requestId("request_id")
                        .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .pageNumber(0)
                        .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .totalItems(0L)
                        .totalPages(0)
                        .build()
                )
                .error(
                    ApiError.builder()
                        .code(400)
                        .message("Order quantity must be greater than zero")
                        .addDetail(
                            ApiError.Detail.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .addData(
                    InstrumentCashFlowStatement.builder()
                        .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                        .filingDate(LocalDate.parse("2025-05-01"))
                        .period("Q1")
                        .periodType(FiscalPeriodType.QUARTERLY)
                        .reportedCurrency("USD")
                        .year(2025)
                        .accountsPayables("accounts_payables")
                        .accountsReceivables("accounts_receivables")
                        .acquisitionsNet("acquisitions_net")
                        .capitalExpenditure("-2600000000")
                        .cashAtBeginningOfPeriod("33743000000")
                        .cashAtEndOfPeriod("29943000000")
                        .changeInWorkingCapital("-3200000000")
                        .commonDividendsPaid("common_dividends_paid")
                        .commonStockIssuance("common_stock_issuance")
                        .commonStockRepurchased("-23000000000")
                        .deferredIncomeTax("deferred_income_tax")
                        .depreciationAndAmortization("2900000000")
                        .effectOfForexChangesOnCash("effect_of_forex_changes_on_cash")
                        .freeCashFlow("25800000000")
                        .incomeTaxesPaid("income_taxes_paid")
                        .interestPaid("interest_paid")
                        .inventory("inventory")
                        .investmentsInPropertyPlantAndEquipment("-2600000000")
                        .longTermNetDebtIssuance("long_term_net_debt_issuance")
                        .netCashProvidedByFinancingActivities("-28300000000")
                        .netCashProvidedByInvestingActivities("-3900000000")
                        .netCashProvidedByOperatingActivities("28400000000")
                        .netChangeInCash("-3800000000")
                        .netCommonStockIssuance("net_common_stock_issuance")
                        .netDebtIssuance("-1500000000")
                        .netDividendsPaid("-3800000000")
                        .netIncome("22200000000")
                        .netPreferredStockIssuance("net_preferred_stock_issuance")
                        .netStockIssuance("net_stock_issuance")
                        .operatingCashFlow("28400000000")
                        .otherFinancingActivities("other_financing_activities")
                        .otherInvestingActivities("other_investing_activities")
                        .otherNonCashItems("other_non_cash_items")
                        .otherWorkingCapital("other_working_capital")
                        .preferredDividendsPaid("preferred_dividends_paid")
                        .purchasesOfInvestments("-9500000000")
                        .salesMaturitiesOfInvestments("8200000000")
                        .shortTermNetDebtIssuance("short_term_net_debt_issuance")
                        .stockBasedCompensation("2500000000")
                        .build()
                )
                .build()

        assertThat(cashFlowStatementGetInstrumentCashFlowStatementsResponse.metadata())
            .isEqualTo(
                ResponseMetadata.builder()
                    .requestId("request_id")
                    .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                    .pageNumber(0)
                    .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                    .totalItems(0L)
                    .totalPages(0)
                    .build()
            )
        assertThat(cashFlowStatementGetInstrumentCashFlowStatementsResponse.error())
            .contains(
                ApiError.builder()
                    .code(400)
                    .message("Order quantity must be greater than zero")
                    .addDetail(
                        ApiError.Detail.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(cashFlowStatementGetInstrumentCashFlowStatementsResponse.data())
            .containsExactly(
                InstrumentCashFlowStatement.builder()
                    .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                    .filingDate(LocalDate.parse("2025-05-01"))
                    .period("Q1")
                    .periodType(FiscalPeriodType.QUARTERLY)
                    .reportedCurrency("USD")
                    .year(2025)
                    .accountsPayables("accounts_payables")
                    .accountsReceivables("accounts_receivables")
                    .acquisitionsNet("acquisitions_net")
                    .capitalExpenditure("-2600000000")
                    .cashAtBeginningOfPeriod("33743000000")
                    .cashAtEndOfPeriod("29943000000")
                    .changeInWorkingCapital("-3200000000")
                    .commonDividendsPaid("common_dividends_paid")
                    .commonStockIssuance("common_stock_issuance")
                    .commonStockRepurchased("-23000000000")
                    .deferredIncomeTax("deferred_income_tax")
                    .depreciationAndAmortization("2900000000")
                    .effectOfForexChangesOnCash("effect_of_forex_changes_on_cash")
                    .freeCashFlow("25800000000")
                    .incomeTaxesPaid("income_taxes_paid")
                    .interestPaid("interest_paid")
                    .inventory("inventory")
                    .investmentsInPropertyPlantAndEquipment("-2600000000")
                    .longTermNetDebtIssuance("long_term_net_debt_issuance")
                    .netCashProvidedByFinancingActivities("-28300000000")
                    .netCashProvidedByInvestingActivities("-3900000000")
                    .netCashProvidedByOperatingActivities("28400000000")
                    .netChangeInCash("-3800000000")
                    .netCommonStockIssuance("net_common_stock_issuance")
                    .netDebtIssuance("-1500000000")
                    .netDividendsPaid("-3800000000")
                    .netIncome("22200000000")
                    .netPreferredStockIssuance("net_preferred_stock_issuance")
                    .netStockIssuance("net_stock_issuance")
                    .operatingCashFlow("28400000000")
                    .otherFinancingActivities("other_financing_activities")
                    .otherInvestingActivities("other_investing_activities")
                    .otherNonCashItems("other_non_cash_items")
                    .otherWorkingCapital("other_working_capital")
                    .preferredDividendsPaid("preferred_dividends_paid")
                    .purchasesOfInvestments("-9500000000")
                    .salesMaturitiesOfInvestments("8200000000")
                    .shortTermNetDebtIssuance("short_term_net_debt_issuance")
                    .stockBasedCompensation("2500000000")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val cashFlowStatementGetInstrumentCashFlowStatementsResponse =
            CashFlowStatementGetInstrumentCashFlowStatementsResponse.builder()
                .metadata(
                    ResponseMetadata.builder()
                        .requestId("request_id")
                        .nextPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .pageNumber(0)
                        .previousPageToken("U3RhaW5sZXNzIHJvY2tz")
                        .totalItems(0L)
                        .totalPages(0)
                        .build()
                )
                .error(
                    ApiError.builder()
                        .code(400)
                        .message("Order quantity must be greater than zero")
                        .addDetail(
                            ApiError.Detail.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .addData(
                    InstrumentCashFlowStatement.builder()
                        .acceptedDate(OffsetDateTime.parse("2025-05-02T14:30:00Z"))
                        .filingDate(LocalDate.parse("2025-05-01"))
                        .period("Q1")
                        .periodType(FiscalPeriodType.QUARTERLY)
                        .reportedCurrency("USD")
                        .year(2025)
                        .accountsPayables("accounts_payables")
                        .accountsReceivables("accounts_receivables")
                        .acquisitionsNet("acquisitions_net")
                        .capitalExpenditure("-2600000000")
                        .cashAtBeginningOfPeriod("33743000000")
                        .cashAtEndOfPeriod("29943000000")
                        .changeInWorkingCapital("-3200000000")
                        .commonDividendsPaid("common_dividends_paid")
                        .commonStockIssuance("common_stock_issuance")
                        .commonStockRepurchased("-23000000000")
                        .deferredIncomeTax("deferred_income_tax")
                        .depreciationAndAmortization("2900000000")
                        .effectOfForexChangesOnCash("effect_of_forex_changes_on_cash")
                        .freeCashFlow("25800000000")
                        .incomeTaxesPaid("income_taxes_paid")
                        .interestPaid("interest_paid")
                        .inventory("inventory")
                        .investmentsInPropertyPlantAndEquipment("-2600000000")
                        .longTermNetDebtIssuance("long_term_net_debt_issuance")
                        .netCashProvidedByFinancingActivities("-28300000000")
                        .netCashProvidedByInvestingActivities("-3900000000")
                        .netCashProvidedByOperatingActivities("28400000000")
                        .netChangeInCash("-3800000000")
                        .netCommonStockIssuance("net_common_stock_issuance")
                        .netDebtIssuance("-1500000000")
                        .netDividendsPaid("-3800000000")
                        .netIncome("22200000000")
                        .netPreferredStockIssuance("net_preferred_stock_issuance")
                        .netStockIssuance("net_stock_issuance")
                        .operatingCashFlow("28400000000")
                        .otherFinancingActivities("other_financing_activities")
                        .otherInvestingActivities("other_investing_activities")
                        .otherNonCashItems("other_non_cash_items")
                        .otherWorkingCapital("other_working_capital")
                        .preferredDividendsPaid("preferred_dividends_paid")
                        .purchasesOfInvestments("-9500000000")
                        .salesMaturitiesOfInvestments("8200000000")
                        .shortTermNetDebtIssuance("short_term_net_debt_issuance")
                        .stockBasedCompensation("2500000000")
                        .build()
                )
                .build()

        val roundtrippedCashFlowStatementGetInstrumentCashFlowStatementsResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(
                    cashFlowStatementGetInstrumentCashFlowStatementsResponse
                ),
                jacksonTypeRef<CashFlowStatementGetInstrumentCashFlowStatementsResponse>(),
            )

        assertThat(roundtrippedCashFlowStatementGetInstrumentCashFlowStatementsResponse)
            .isEqualTo(cashFlowStatementGetInstrumentCashFlowStatementsResponse)
    }
}
